kurusugawa-computer/annofab-cli

annofabcli/__main__.py
annofabcli/delete_users.py
annofabcli/list_users.py

複数のプロジェクトのユーザを表示して、削除するテストは終わっています。
組織単位の表示・削除テストはまだしてません。

ユーザの表示と削除機能を追加。

---

README.md
annofabcli/annotation_specs/list_annotation_specs_label.py
annofabcli/annotation_specs/print_label_color.py
annofabcli/input_data/list_input_data_merged_task.py
annofabcli/statistics/summarize_task_count.py
annofabcli/statistics/summarize_task_count_by_task_id.py
annofabcli/statistics/summarize_task_count_by_user.py
annofabcli/statistics/visualize_statistics.py
annofabcli/supplementary/list_supplementary_data.py
annofabcli/task/list_tasks_added_task_history.py

close #260
* statistics系のコマンドを、アノテーションユーザロールでも実行できるようにする 
* [supplementary list] コマンドライン引数に`--task_id`も渡せるようにする

アノテーションユーザロールでもできるコマンドを増やす

---

README.md
annofabcli/experimental/mask_user_info.py
annofabcli/experimental/mask_visualization_dir.py
tests/test_local_experimental.py
tests/test_main.py

* マスク対象外ユーザのbiographyが書き換わってしまった不具合を対応
* `experimental  mask_visualization_dir`
* `experimental  mask_user_info`

[experimental mask visualization_dir] マスク対象外ユーザのbiographyが書き換わってしまった不具合を対応

---

README.md
annofabcli/inspection_comment/list_inspections.py
annofabcli/inspection_comment/list_unprocessed_inspections.py
annofabcli/task/list_tasks.py
annofabcli/task_history/list_task_history.py
tests/test_main.py

* `task list`：`--task_json`
* `task_history list`：`--task_history_json`
* `inspection_comment list`：`--inspection_comment_json`
* `inspection_comment list_unprocessed`：`--inspection_comment_json`

Deprecated: `list`系コマンドで全件ファイルJSONを渡さないように変更する

---

annofabcli/statistics/database.py

slackの`#triad_tjl3_notice`に出力している集計botについて、4/2の集計にて4/1に着手したタスクが集計対象にならなかった。
調査したところ、以下のコマンドのデバッグログの中に表示される対象タスク件数が不足していた。(0件と出た)
```sh
poetry run annofabcli statistics visualize --minimal --project_id triad-133f1aa1-b28dd2b7-7ade-4739-b5dc-464f68b4eb21 --start_date 2021-04-01 --end_date 2021-04-02 --output_dir <out_dir> --task_query '{"status":"complete"}' 
```
デバッグ出力を加えた検証の結果、タスクの登録日時をタスク開始日時としており、--start-dateより前に登録したタスクが除外されているためではないかと考えた。(集計対象からはずれたデータは、3/30および3/31に登録されており辻褄が合った)
AnnoFabのリリースノートを見ると、以下でタスク履歴にかんして修正が入っている。
https://annofab.com/docs/releases/2020.html#v01020
タスク作成時に履歴が入るようになったとのこと。
annofab-cliの実装では、必ず最初の (= Litstの0番目の) 履歴からタスク開始日時を取得するようになっているため、最初の履歴が「(タスク作成)」の場合、タスク登録日時がタスク開始日時として取得されてしまう。おそらくこれが原因と思われる。
「(タスク作成)」がある場合は、その履歴をスキップするよう実装を修正した。 …

--start-date で指定した開始日より後に教師付けを開始したタスクが集計対象にならない場合がある問題を修正

---

.github/workflows/release.yml

Fix #571 
`poetry add`時にdev-dependenciesがインストールされていた。
`--lock`オプションを追加することでlockfileの更新だけを行い、`poetry install --no-dev`でpyinstallerをインストールする。

リリースビルド時にdev-dependenciesがインストールされている問題を修正

---

annofabcli/input_data/update_metadata_of_input_data.py
annofabcli/task/update_metadata_of_task.py
docs/command_reference/task/update_metadata.rst
docs/examples/edit_annotation.rst

* デフォルトではメタデータが常に上書きされましたが、`--overwrite`オプションで上書きするかどうかを指定できるようにしました。
* `--parallelism` を指定しました。
* `--batch_size` を削除しました。指定する機会がほとんどないためです。

`task update_metadata`コマンドオプションの改善

---

annofabcli/supplementary/put_supplementary_data.py
annofabcli/task/delete_tasks.py
docs/command_reference/supplementary/put.rst
docs/command_reference/task/delete.rst
tests/test_inspection_comment.py

close #720 
`--delete_input_data`オプションを追加した。

[task delete] タスクが参照している入力データも削除するオプションを追加

---

.travis.yml
.vscode/cspell.json
annofabcli/annotation_specs/list_attribute_restriction.py
tests/test_local_annotation_specs.py

制約情報に属性IDが記載されて見づらい。
```
'line_side' (id='505a3839-361c-4304-a967-00cda40c3293', type='select') DOES NOT EQUAL ''
```
デフォルトでは以下のように属性IDを隠すようにした。
```
'line_side' DOES NOT EQUAL ''
```
`--format`引数で出力フォーマットを変更できるようにしました。
```
$ annofabcli annotation_specs list_attribute_restriction -p prj1 --format text
'line_side' DOES NOT EQUAL ''
$ annofabcli annotation_specs list_attribute_restriction -p prj1 --format detailed_text
'line_side' (id='505a3839-361c-4304-a967-00cda40c3293', type='select') DOES NOT EQUAL ''
```

[annotation_specs list_restrictions] "--format"を追加

---

annofabcli/statistics/database.py
annofabcli/statistics/linegraph.py
annofabcli/statistics/visualization/dataframe/user_performance.py
annofabcli/statistics/visualization/dataframe/worktime_per_date.py

* `stat_visualization merge` : bokehに関するエラーを修正
* update document
* `statistics visualize` : 全件ファイルのダウンロードを非同期から同期的にする。同期的でも速度はそこまで変わらないため。その分コードの見通しがよくなるため。

`stat_visualization merge` : bokehの3.0バージョンアップの対応漏れに対処

---

.travis.yml
poetry.lock
pyproject.toml

* 開発用のライブラリをグループ化した
* TravisCI上で、必要なライブラリしかインストールしないようにした
* pyproject.tomlで、`poetry build`で生成されるclassifiersは重複していたので、削除した

poetryのdependenciesをグループ化する

---

annofabcli/project/copy_project.py
annofabcli/statistics/summarize_task_count_by_task_id_group.py
pyproject.toml
tests/statistics/test_summarize_task_count_by_task_id_group.py

* ruffでpyupgradeを有効にする
* `project copy`で待ち時間を1分以下にする。コピーが1分で終わるときがあるため

ruffでpyupgradeを有効にする

---

.github/workflows/release.yml
.travis.yml
.vscode/settings.json
poetry.lock
pyproject.toml

* dev, publishグループをオプショナルにした。開発時は利用しないので。
* poetry installのやり方を変えた

pypyroject.tomlの依存ライブラリのグループ化を修正

---

annofabcli/common/image.py
tests/common/test_image.py

塗りつぶしアノテーションを8bit grayscaleの画像に変換する

---

annofabcli/statistics/visualization/dataframe/cumulative_productivity.py
annofabcli/statistics/visualization/dataframe/project_performance.py
annofabcli/statistics/visualization/dataframe/task.py
annofabcli/statistics/visualization/dataframe/user_performance.py
annofabcli/statistics/visualization/dataframe/worktime_per_date.py
poetry.lock
pyproject.toml

https://qiita.com/yuji38kwmt/items/b5da6ed521e827620186
`pandas.to_datetiem`関数に`format="ISO8601"`を指定する
https://qiita.com/yuji38kwmt/items/9aeed6e8f54d0ebf3720

bokeh3.1, pandas2.0へのバージョンアップ対応

---

annofabcli/statistics/table.py

以下の警告メッセージに対応した。
```
tests/statistics/test_table.py::TestTable::test_create_annotation_count_ratio_df
/workspaces/annofab-cli/annofabcli/statistics/table.py:350: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
return e / float(e.sum())
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

pandasの警告に対応する

---

annofabcli/input_data/change_input_data_name.py
annofabcli/input_data/put_input_data.py
annofabcli/supplementary/put_supplementary_data.py

以下の警告が出ないようにしました。
```
tests/test_input_data.py::TestCommandLine::test_scenario
/workspaces/annofab-cli/.venv/lib/python3.11/site-packages/dataclasses_json/mm.py:271: UserWarning: Unknown type str at ChangedInputData.input_data_name: str It's advised to pass the correct marshmallow type to `mm_field`.
warnings.warn(
```
https://qiita.com/yuji38kwmt/items/3421f946b0cd892d6e10

dataclasses-jsonの`Unknown type str at ChangedInputData.input_data_name`のような警告wo

---

annofabcli/statistics/list_annotation_count.py

```
$ annofabcli statistcs list_annotation_count --type attribute -p ${PROJECT_ID} -o out.csv
```
`out.csv`の列の順番は以下のように、label1, label2でまとまっていませんでした。
```
label1, attr1, true
label1, attr1, false
label2, attr2, true
label2, attr2, false
label1, attr1, ""
label2, attr2, ""
```
3番目の属性値用の列は、アノテーション仕様の定義に関わらず空欄になる可能性があるためです。
`out.csv`の列が以下のような順番になるよう、変更しました。
```
label1, attr1, true
label1, attr1, false
label1, attr1, ""
label2, attr2, true
label2, attr2, false
label2, attr2, ""
```

`statistcs list_annotation_count --type attribute`：列の順番を変更しました。

---

annofabcli/common/cli.py
annofabcli/common/exceptions.py

MFAが有効化されているユーザーで、コマンドライン引数に`--mfa_code`を指定しない場合、標準入力からMFA codeを入力させる。
そうすれば、コマンドを終了することなく処理を続行できるため。

標準入力からMFA codeを入力させる

---

annofabcli/common/cli.py
annofabcli/statistics/summarize_task_count.py

最新のタスク情報を参照する場合、タスク全件ファイルをダウンロードするよりも、`getTasks` APIを実行した方がすぐに結果を取得できます。
そのようなケースに対応するため、`--execute_get_tasks_api`オプションを追加しました。このオプションを指定すると、`getTasks` APIを実行してタスク一覧を取得します。

`statisitcs summarize_task_count` : `--execute_get_tasks_api`オプションを追加

---

annofabcli/statistics/visualization/dataframe/user_performance.py

受入完了状態のタスクが一つもない状態で以下のコマンドを実行すると、エラーが発生した。
```
$ annofabcli statistics visualize -p prj1 -tq '{"phase":"acceptance"}'
WARNING  : 2024-01-22 09:38:43,279 : annofabcli.statistics.visualize_statistics : project_id='foo'であるプロジェクトでのファイル出力に失敗しました。
Traceback (most recent call last):
File "/home/vagrant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/annofabcli/statistics/visualize_statistics.py", line 91, in wrapped
return function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vagrant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/annofabcli/statistics/visualize_statistics.py", line 135, in write_user_performance
user_performance = UserPerformance.from_df(
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vagrant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/annofabcli/statistics/visua …
```

`statitics visualize` : `メンバごとの生産性と品質.csv`の出力に失敗する不具合を修正

---

annofabcli/__main__.py
annofabcli/statistics/visualization/dataframe/user_performance.py

```
vscode@example:/workspaces/annofab-cli$ poetry run annofabcli my_account get --annofab_user_id foo --annofab_password bar
INFO     : 2024-01-25 06:52:20,480 : annofabcli.__main__            : argv=['/workspaces/annofab-cli/.venv/bin/annofabcli', 'my_account', 'get', '--annofab_user_id', '***', '--annofab_password', '***']
```

`--annofab_user_id`, `--annofab_password`を指定したときは、その値をマスクしてログに出力する

---

annofabcli/stat_visualization/mask_visualization_dir.py

折れ線グラフに60人表示されるようになったので、`--exclude_masked_user_for_line_graph`を使用する機会は少ないと考え、削除しました。

`stat_visualization mask_user_info` : `--exclude_masked_user_for_line_graph`引数を削除

---

annofabcli/stat_visualization/merge_visualization_dir.py
annofabcli/statistics/visualization/dataframe/task.py
annofabcli/statistics/visualization/dataframe/whole_productivity_per_date.py
annofabcli/statistics/visualize_statistics.py
tests/statistics/visualization/dataframe/test_whole_productivity_per_date.py

マージ対象ディレクトリにある`教師付開始日毎の生産量と生産性.csv`や`日毎の生産量と生産性.csv`を読み込み、合算した値をファイル出力しました。
`タスクlist.csv`と`ユーザ_日付list-作業時間.csv`を読み込み合算して、`教師付開始日毎の生産量と生産性.csv`や`日毎の生産量と生産性.csv`を出力するようにしました。

`stat_visualization merge` : マージ対象ディレクトリに`教師付開始日毎の生産量と生産性.csv`や`日毎の生産量と生産性.csv`が存在しなくても、ファイルを出力できるようにしました。

---

annofabcli/statistics/list_annotation_count.py
annofabcli/statistics/summarize_task_count_by_task_id_group.py

pandasの以下の警告を修正しました。
```
tests/statistics/test_list_annotation_count.py::TestLabelCountCsv::test_print_csv_by_input_data
/workspaces/annofab-cli/annofabcli/statistics/list_annotation_count.py:671: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
df.fillna(0, inplace=True)
tests/statistics/test_list_annotation_count.py::TestAttributeCountCsv::test_print_csv_by_input_data
/workspaces/annofab-cli/annofabcli/statistics/list_annotation_count.py:566: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call …
```

pandasのFutureWarningを対応

---

annofabcli/common/pandas.py
annofabcli/statistics/list_annotation_count.py
annofabcli/statistics/summarize_task_count_by_task_id_group.py
annofabcli/statistics/visualization/dataframe/project_performance.py
tests/test_stat_visualization.py

https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#deprecate-aliases-m-q-y-etc-in-favour-of-me-qe-ye-etc-for-offsets
pandasのバージョンを見て、frequencyコードを変えるようにした。
* pandas 2.2.0以上ならば"ME"
* そうでないならば"M"

Python3.8でpandas操作に失敗する不具合を修正

---

annofabcli/__main__.py
annofabcli/statistics/summarize_task_count.py
annofabcli/statistics/visualization/dataframe/project_performance.py

```
tests/test_statistics.py::TestCommandLine::test_summarize_task_count
/workspaces/annofab-cli/annofabcli/statistics/summarize_task_count.py:123: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
summary_df = df.pivot_table(
```

pandas 2.2以上ならばCopy-on-Writeの警告を出すようにしました。

---

annofabcli/filesystem/mask_user_info.py

`--csv_header`という名前では、「ヘッダ行数を指定する」ことが分からないので、具体的な名前に変更しました。

`filesystem mask_user_info`のコマンドライン引数`--csv_header`を`--csv_header_row_count`に変更しました。

---

annofabcli/statistics/visualization/dataframe/actual_worktime.py
annofabcli/task/update_metadata_of_task.py

`putTask` APIはアノテーションユーザーロールでは実行できないが、`patchTasksMetadata` APIならばアノテーションユーザーロールでも実行できる。
したがって、`putTask` APIではなく`patchTasksMetadata` APIでメタデータを更新するように変更した。

`task update_metadata`: メタデータを更新するAPIを`putTask`から`patchTasksMetadata`に変更する。

---

annofabcli/statistics/visualization/dataframe/user_performance.py
tests/statistics/visualization/dataframe/test_user_performance.py

`全体の生産性と品質.csv`を出力するときにエラーが発生
```
Traceback (most recent call last):
File "index.pyx", line 768, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
File "/home/kcitde/.cache/pypoetry/virtualenvs/kcitde-annotation-to-slack-OBHEOexS-py3.11/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
raise KeyError(key) from err
KeyError: 'stdev__monitored_worktime_hour/annotation_count'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/kcitde/.cache/pypoetry/virtualenvs/kcitde-annotation-to-slack-OBHEOexS-py3.11/lib/python3.11/site-packages/pandas/core/indexes/multi.py", line 3053, in get_loc
return self._engine.get_loc(key)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "index.pyx", line 771, in …
```

`statistics visualize` : `全体の生産性と品質.csv`を出力したときに発生するエラーを修正

---

annofabcli/statistics/visualize_statistics.py

マージは `merge`コマンドで実行した方が機能がシンプルになるので、`--merge`引数を削除した。

`statistics visualize` : `--merge`引数を削除

---

annofabcli/statistics/visualization/dataframe/user_performance.py
annofabcli/statistics/visualization/dataframe/worktime_per_date.py
annofabcli/statistics/visualization/visualization_source_files.py
annofabcli/statistics/visualize_statistics.py
tests/statistics/visualization/dataframe/test_user_performance.py

* ダウンロードしたアノテーションZIPなどを残すために`--temp_dir`引数を追加しました。
* ダウンロードしたアノテーションZIPなどから可視化情報を出力できるようにするるため、`--not_download`オプションを追加しました。このオプションを指定するとアノテーションZIPをダウンロードせずに、`--temp_dir`に存在するファイルを読み込んで可視化情報を出力します。

`statistics visualize` : 引数`--temp_dir`, `--not_downlod`を追加

---

annofabcli/statistics/scatter.py
annofabcli/statistics/visualization/dataframe/user_performance.py

散布図の項目に以下を追加しました。
* `first_working_date` : 作業を開始した日
* `working_days` : 作業日数
* x,y : X座標の値とY座標の値

`statistics visualize`: 散布図のツールチップに項目を追加する

---

annofabcli/statistics/scatter.py
annofabcli/statistics/visualization/dataframe/user_performance.py
poetry.lock
pyproject.toml

散布図にたくさんのユーザーが表示されていると（たとえば40人）、特定のユーザーがどこに位置しているか探すのが難しい。
複数選択ボックスで、特定のユーザーを探せるようにした。
`MultiChoice`ボックスで選択すると、散布図に表示されているユーザー名を太字にしてフォントサイズを大きくした。
* 円形サイズを変えなかった理由：円形サイズで作業時間を表す散布図があるため
* ユーザー名は1個ずつプロットしているため、出力に時間がかかる。 https://qiita.com/yuji38kwmt/items/3da82782c6f32f868720#html%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E5%87%BA%E5%8A%9B%E3%81%AB%E6%99%82%E9%96%93%E3%81%8C%E3%81%8B%E3%81%8B%E3%82%8B 参照
* ユーザー名は1個ずつプロットしているため、ファイルサイズが増えた
* ユーザー数が47で散布図のファイルサイズは200KB~300KB

`statistics visualize` : 散布図で特定のユーザーを探せるようにする

---

annofabcli/annotation_specs/export_annotation_specs.py

アノテーション仕様画面のエクスポート機能に合わせて、出力結果からproject_idを除去する。

`annotation_specs export` : 出力結果から`project_id`を除去する

---

annofabcli/__main__.py

`warn_pandas_copy_on_write()`が実行されていなかったので、実行されるように変更しました。

`__main__`の処理の変更

---

annofabcli/statistics/list_annotation_count.py
annofabcli/statistics/list_annotation_duration.py
annofabcli/statistics/subcommand_statistics.py
docs/command_reference/statistics/index.rst
docs/command_reference/statistics/list_annotation_count.rst
docs/command_reference/statistics/list_annotation_duration.rst
docs/command_reference/statistics/list_annotation_duration/out_by_attribute.csv
docs/command_reference/statistics/list_annotation_duration/out_by_label.csv
tests/statistics/test_list_annotation_duration.py

```
$ annofabcli statistics list_annotation_duration --project_id prj1 --format pretty_json --output out.json
```
```
{
"annotation_duration_second": 123.456,
"annotation_duration_second_by_label": {
"car": 60.123,
"bike": 10.123,
...
},
"annotation_duration_second_by_attribute": {
"car": {
"occlusion": {
"false": 10.123,
"true": 20.123
},
"type": {
"normal": 10.123,
"bus":20.123
}
},
"bike": {
"occlusion": {
"false": 10.123,
"true": 20.123
}
}
},
"task_id": "task1",
"status": "complete",
"phase": "acceptance",
"phase_stage": 1,
"input_data_id": "input1",
"input_data_name": "input1"
}
```

`statistics list_annotation_duration` : コマンドを作成

---

annofabcli/filesystem/merge_annotation.py
annofabcli/statistics/list_annotation_count.py

`encoding="utf-8"`を指定しないと、Windows環境で実行する際に`UnicodeDecodeError`が発生するため、`encoding="utf-8"`を指定します。

ファイルオープン時に`encoding="utf-8"`を指定する

---

annofabcli/statistics/linegraph.py
annofabcli/statistics/scatter.py
annofabcli/statistics/visualization/dataframe/cumulative_productivity.py
annofabcli/statistics/visualization/dataframe/productivity_per_date.py
annofabcli/statistics/visualization/dataframe/worktime_per_date.py

ユーザーごとにプロットする折れ線グラフで、ユーザー数が40人以上だと、特定のユーザーの折れ線を探すのに時間がかかる。
そこで、"MultiChoice" widgetを使って、ユーザー情報を入力できるようにした。該当するユーザーの折れ線グラフは太くなるように変更した。

`statistics visualize`: 折れ線グラフで、指定したユーザーの折れ線を太くする

---

annofabcli/statistics/visualization/dataframe/user_performance.py
annofabcli/statistics/visualization/dataframe/whole_productivity_per_date.py

以下の折れ線グラフのtooltipに`working_user_count`を追加しました。
* `折れ線-横軸_日-全体.html`
* `累積折れ線-横軸_日-全体.html`
「X日の作業時間が40時間」だったときに、「何人が作業しているから50時間だった」というざっくりとした情報を把握できるようにするためです。
生産性などの指標にinfが含まれている場合、四分位数を求める際にnumpyのRuntimeWarningが発生します。
```
RuntimeWarning: invalid value encountered in multiply
lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
```
infが含まれていてもRuntimeWarningが発生しないようにするため、infを除いて四分位数を求めるようにしました。

`statistics visualize` : tooltipにuser_countを追加

---

pyproject.toml

`trailing-comma-on-bare-tuple` (COM818) はバグに気づけるかもしれないので、flake8-commas (COM)を有効にしました。
ただし、末尾のカンマの有無は気にしていないので、`COM812`は無視する設定にしました。

Ruffのflake8-commas (COM)を有効にする

---

annofabcli/common/cli.py
annofabcli/common/download.py
annofabcli/experimental/list_out_of_range_annotation_for_movie.py
poetry.lock
pyproject.toml

* `annofabapi`の機能を使って、MFAコードを標準入力から入力できるようにしました。
* Ruffの`FBT001`, `FBT002`を`noqa`ディレクティブで無視しました。

MFAコードを間違えて入力したときに、再度MFAコードを入力できるようにしました。

---

annofabcli/__main__.py
tests/test____main__.py

`--annofab_password a --annofab_password 2`と複数した場合、1つ目の`a`しかマスクされなかった。
`--annofab_password a --annofab_password 2`は`--annofab_password *** --annofab_password **`と複数マスクされるように変更した。

sensitiveな情報をログに出力しないようにする

---

annofabcli/statistics/visualization/dataframe/whole_performance.py

```
$ poetry run annofabcli statistics visualize -p db363f62-405b-424f-99aa-d9dae080aa4f   -o out -tq '{"status":"complete"}' --output_only_text --minimal 
DEBUG    : 2024-06-10 08:49:15,400 : annofabcli.statistics.visualize_statistics : project_id='db363f62-405b-424f-99aa-d9dae080aa4f' :: 集計対象タスクは 0 / 8 件です。
WARNING  : 2024-06-10 08:49:15,410 : annofabcli.statistics.visualization.dataframe.task_worktime_by_phase_user : タスク一覧が0件です。
WARNING  : 2024-06-10 08:49:15,414 : annofabcli.statistics.visualization.dataframe.task_worktime_by_phase_user : データが0件のため、out/20240610/task-worktime-list-by-user-phase.csv は出力しません。
WARNING  : 2024-06-10 08:49:16,423 : annofabcli.statistics.visualization.dataframe.user_performance : データが0件のため、out/20240610/メンバごとの生産性と品質.csv は出力しません。
WARNING  : 2024-06-10 …
```

`statistics visualize` : タスクが存在していて一度も作業されていないプロジェクトでエラーが発生

---

annofabcli/annotation/dump_annotation.py
annofabcli/task/update_metadata_of_task.py
docs/command_reference/task/update_metadata.rst

以下のコマンドで、タスクごとにメタデータを指定できるようにしました。
```
$ annofabcli task update_metadata --project_id prj1 --metadata_by_task_id '{ "task1": {"priority":1},  "task2": {"priority":2}}'
```

`task update_metadata` : タスクごとにメタデータを指定できるようにしました。

---

annofabcli/input_data/update_metadata_of_input_data.py
annofabcli/task/update_metadata_of_task.py
docs/command_reference/input_data/update_metadata.rst

`all_metadata.json`というJSONファイルに対して、以下のコマンドで入力データごとにメタデータを指定できるようにしました。
```
{
"input_data1": {"country":"japan"},
"input_data2": {"country":"us"}
}
```
```
$ annofabcli input_data update_metadata --project_id prj1  --metadata_by_input_data_id file://all_metadata.json
```

`input_data update_metadata` : 入力データごとにメタデータを指定できるようにしました。

---

annofabcli/annotation/annotation_query.py
annofabcli/annotation_specs/list_annotation_specs_label.py
annofabcli/common/facade.py
poetry.lock
pyproject.toml
tests/test_annotation.py

* annofabapiのバージョンアップに伴い、`annofabapi.utils.get_message_for_i18n`を`annofabapi.util.annotation_specs.get_english_message`に置き換えました。

annofabapiをv0.74.0に更新

---

annofabcli/annotation/annotation_query.py
annofabcli/annotation/change_annotation_attributes.py
annofabcli/annotation/copy_annotation.py
annofabcli/annotation_specs/list_annotation_specs_label.py
annofabcli/common/cli.py
annofabcli/common/facade.py
annofabcli/common/image.py
annofabcli/filesystem/merge_annotation.py
annofabcli/statistics/list_annotation_count.py
annofabcli/statistics/list_annotation_duration.py
annofabcli/statistics/visualization/dataframe/actual_worktime.py
annofabcli/statistics/visualization/dataframe/annotation_count.py
annofabcli/statistics/visualization/dataframe/inspection_comment_count.py
annofabcli/statistics/visualization/dataframe/task.py
annofabcli/statistics/visualization/dataframe/task_history.py
annofabcli/statistics/visualization/dataframe/task_worktime_by_phase_user.py
annofabcli/statistics/visualization/dataframe/user.py
annofabcli/statistics/visualization/dataframe/worktime_per_date.py
annofabcli/task/copy_tasks.py
pyproject.toml

もともと、コマンドライン引数 `--annotation_query` の`label`キーは必須でした。
属性値だけで絞り込みたいときがあるので、`label`キーをオプショナルにしました。
ただし、`label`と`attribute`のどちらかを指定する必要があります。
* `batchUpdateAnnotations` APIのリクエストボディを`BatchAnnotationRequestItemPutV1`から`BatchAnnotationRequestItemPutV2`に変更しました。
* Ruffの`TRY003`を`pyproject.toml`で無視するようにしました。

`annotation change_attributes`など: `--annotation_query`の`label_id`をオプショナルにしました。

---

.travis.yml

Windowsでも動作できるようにするため、TravisCIのWindows環境でテストを実行していた。
しかし、TravisCIで実行しているテストケースは少ないため、TravisCIでWindows固有のバグが見つかることはほとんどない。
また、TravisCIでのWindowsのテストはUbuntu環境でのテストと比べると環境構築に時間かかって遅い。
したがって、開発効率を上げるためTravisCIのWindows環境でのテストをやめることにした。

TravisCIでWindowsのテストを実行しないようにする

---

annofabcli/input_data/list_all_input_data.py
annofabcli/input_data/list_input_data.py
annofabcli/input_data/list_input_data_merged_task.py
annofabcli/input_data/utils.py
annofabcli/supplementary/list_supplementary_data.py

以下のコマンドの出力結果から、不要な情報を出力しないようにしました。
* `input_data list_all`
* `input_data list`
* `input_data list_merged_task`
* `supplementary list`
削除したキーは以下の通りです。
* `url` : システム内部用のプロパティのため。
* `original_input_data_path`: システム内部用のプロパティのため
* `etag` : annofab-cliの出力結果で参照することがなさそうなので。もしETagを利用するなら、annofab-api-python-clientを使うはず。
* `url`には認証済み一時URLが格納されています。セキュリティ的に認証済一時URLをファイルなどに出力するのはよろしくないので、`url`を出力しないようにしました。
* 入力データ全件ファイルでは、`url`と`etag`にはnullが格納されています。入力データ全件ファイルを利用する`list_all`コマンドで、入力データ全件ファイルを利用しない`list`コマンドの出力結果を揃えるため、`etag`も出力しないようにしました。

入力データと補助情報から不要な情報（システム内部用のパラメータなど）を出力しないようにしました。

---

annofabcli/supplementary/list_supplementary_data.py

* `--task_id` : タスクIDを指定しても、どのタスクに関連する補助情報か分からないため（補助情報はタスクで入力データに紐づく）、かえって混乱するかと思い削除しました。
* `--query` : 利用用途が少ないため削除しました。
* `--csv_format` : 利用用途が少ないため削除しました。
* `--input_data_id`を指定しない場合は、入力データ全件ファイルをダウンロードして、すべての入力データに紐づく補助情報を参照するようにしました。そうすることで、どの入力データに補助情報が存在するか分からない状態でもコマンドを利用できるためです。
* `--parallelism`を追加しました。

`supplementary list`: コマンドライン引数を変更しました

---

README.md
docker-build.sh
docker/Dockerfile

複数のPythonバージョンや複数のOS(Linux, Windows)で動作するように努めているため（動作確認はできていないが）、ユーザー用の`Dockerfile`を削除しました。
`Dockerfile`の中身は`pip install annofabcli`を実行しているだけなので、この`Dockerfile`を削除しても大きな問題ないはないと考えています。

`annofab-cli`のユーザー用のDockerfileを削除しました

---

annofabcli/project/put_project.py
docs/command_reference/project/put.rst

３次元プロジェクトを作成できるようにするため、`--custom_project_type`を追加しました。`--custom_project_type 3d`を指定すると、ビルトインのプラグインIDが設定されます。
あわせて、`--configuration`でプロジェクトの設定情報を指定できるようんしました。

`project put` : `--custom_project_type`, `--configuration`オプションを追加

---

annofabcli/statistics/visualization/dataframe/cumulative_productivity.py
annofabcli/statistics/visualization/project_dir.py

以下の理由から、 `累積折れ線-横軸_タスク数-教師付者用.html`を出力しないようにしました。
* 累積折れ線グラフでタスクあたりの作業時間を生産性の指標として確認するケースはあまりないため
* 入力データあたりの作業時間の方が、生産性の指標としてより表現できている
* 累積折れ線グラフでタスクあたりの差戻し回数を品質の指標として確認するケースはあまりないため
* 差戻しはルールの変更などでも行われるため、そもそも品質の指標として使いにくい

`statistics visualize` : `累積折れ線-横軸_タスク数-教師付者用.html`を出力しないようにする

---

annofabcli/statistics/visualization/dataframe/cumulative_productivity.py
annofabcli/statistics/visualization/dataframe/productivity_per_date.py
annofabcli/statistics/visualization/dataframe/task.py
annofabcli/statistics/visualization/dataframe/user_performance.py
annofabcli/statistics/visualization/dataframe/whole_productivity_per_date.py
annofabcli/statistics/visualization/dataframe/worktime_per_date.py
annofabcli/statistics/visualization/project_dir.py
annofabcli/statistics/visualize_statistics.py

HTMLファイルだけでは、どのプロジェクトに対してどのようにグラフを出力したのかが分からないため、グラフ上部にメタデータを表示できるようにしました。

`statistics visualize` : グラフにメタデータを表示する

---

annofabcli/stat_visualization/mask_visualization_dir.py
annofabcli/stat_visualization/merge_visualization_dir.py
annofabcli/statistics/visualization/dataframe/project_performance.py
annofabcli/statistics/visualization/dataframe/task.py
annofabcli/statistics/visualization/dataframe/task_worktime_by_phase_user.py
annofabcli/statistics/visualization/dataframe/user_performance.py
annofabcli/statistics/visualization/dataframe/whole_performance.py
annofabcli/statistics/visualization/dataframe/whole_productivity_per_date.py
annofabcli/statistics/visualization/dataframe/worktime_per_date.py
annofabcli/statistics/visualization/project_dir.py
annofabcli/statistics/visualize_statistics.py
tests/statistics/visualization/dataframe/test_user_performance.py
tests/statistics/visualization/dataframe/test_whole_performance.py

#645 
以下のCSVとそのCSVから生成したグラフでは、`--task_completion_criteria accpetance_reached`を指定したときに受入作業時間を0にしました。
* `メンバごとの生産性と品質.csv`
* `全体の生産性と品質.csv`
* `日毎の生産量と生産性.csv`
* `教師付開始日毎の生産量と生産性.csv`
受入フェーズに到達したらタスクが完了したことになるため、受入作業時間は不要だからです。

`statistics visualize` : `--task_completion_criteria accpetance_reached`を指定したときに、受入作業時間を0にする

---

annofabcli/stat_visualization/mask_visualization_dir.py
annofabcli/stat_visualization/merge_visualization_dir.py
annofabcli/stat_visualization/write_graph.py
annofabcli/statistics/visualization/dataframe/cumulative_productivity.py
annofabcli/statistics/visualization/dataframe/productivity_per_date.py
annofabcli/statistics/visualization/dataframe/worktime_per_date.py
annofabcli/statistics/visualize_statistics.py
tests/data/statistics/task-worktime-by-user-phase.csv
tests/statistics/visualization/dataframe/test_cumulative_productivity.py
tests/statistics/visualization/dataframe/test_productivity_per_date.py

#630 
以下のグラフの表示方法を変更しました。
* `折れ線-横軸_教師付開始日-縦軸_アノテーション単位の指標-教師付者用.html`
* `累積折れ線-横軸_アノテーション数-教師付者用.html`

`statistics visualize` : １個のタスクを複数人で作業した場合に、`折れ線-横軸_教師付開始日`などのグラフに対応するようにしました。

---

annofabcli/statistics/visualization/dataframe/productivity_per_date.py

以下の警告メッセージが出ないように対応しました。
```
FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
df2 = df2.fillna(0).infer_objects(copy=False)
```

`statisitcs visualize` : pandasの警告メッセージに対応しました

---

annofabcli/statistics/visualize_video_duration.py

以下のエラーが発生していたのを修正しました。
```
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```

`statistics visualize_video_duration` : タスクに含まれている入力データが見つからないときにエラーが発生する問題を修正しました。

---

annofabcli/statistics/visualization/visualization_source_files.py
annofabcli/statistics/visualize_statistics.py

`--annotation_count_csv`を指定した場合は、アノテーションZIPをダウンロードする必要はないので、ダウンロードしないようにした。
３次元プロジェクトでセグメントを利用している場合、アノテーションZIPは1GBを超えることがあるので、このようなケースでは処理時間が大きく短くなる。

`statistics visualize` : "--annotation_count_csv"を指定したときは、対象プロジェクトのアノテーションZIPをダウンロードしないようにする

---

annofabcli/statistics/visualization/dataframe/input_data_count.py
annofabcli/statistics/visualization/dataframe/task.py
annofabcli/statistics/visualize_statistics.py
docs/command_reference/statistics/visualize.rst
tests/statistics/visualization/dataframe/test_task.py

close #1327
タスクに作業しない参照用のフレームが含まれている場合、生産した入力データ数が正しくないため、入力データ数をカスタマイズできるオプションを作りました。

`statistics visualize` : `--input_data_count_csv`オプションを追加しました。

---

annofabcli/input_data/put_input_data.py
docs/command_reference/input_data/put.rst
tests/input_data/test_put_input_data.py

close #1265
`input_data_id`が指定されないときは、UUID v4が設定されます。
これは、Annofabの画面と同じ挙動です。
input_data_idはアノテーションZIP内のJSONファイル名に使われます。`{input_data_id}.json`というフォーマットです。
input_data_idがUUIDだと、JSONファイルをプログラムで扱いにくいです。
ある画像に対するJSONファイルを取得するには、まずinput_data_nameを特定して、その後入力データを取得して、input_data_idを知る必要があります。
したがって、input_data_idには、input_data_nameと同じ値を設定するプロジェクトが多いです。
input_data_idが指定されないときは、UUIDでなくinput_data_nameに近い値を設定するようにしました。
具体的には以下のように変換します。
* `input_data_name`から拡張子を除く（`{input_data_id}.json`というように使われるため、拡張子があると少し分かりくにため。問題ではない）
* IDに使えない文字以外は`__`に変換する
補助情報の登録も同様の処理が必要です。

`input_data put` : input_data_idが指定されないときに、UUIDではなくinput_data_nameに近い値が設定されるようにしました。

---

annofabcli/input_data/put_input_data.py
tests/input_data/test_put_input_data.py

#1347 では、input_data_nameから拡張子を除いたものをinput_data_idにしました。
input_data_idはファイル名に使われるため、拡張子が含まれていない方がよいと考えたためです。
しかし、拡張子が含まれていても特に問題はありません。
また機械的な変更の方が、ユーザーが予測しやすくなると考え、拡張子を除去しないようにしました。

`input_data put` : input_data_idが未指定のときに、input_data_nameの拡張子を除かないようにする

---

annofabcli/project_member/put_project_members.py
annofabcli/supplementary/put_supplementary_data.py
docs/command_reference/supplementary/put.rst
tests/test_supplementary.py

`--csv`に渡すCSVファイルのフォーマットはヘッダなしでした。
以前は`supplementary_data_number`は必須でしたが、自動的に決めることができるためオプショナルにしたいです。
しかし、CSVは「ヘッダなし」であるため、`supplementary_data_number`をオプショナルに変更できません。
そこで、CSVのフォーマットを破壊的に変更して、「ヘッダあり」にしました。
-----
他のコマンドも、ヘッダなしCSVからヘッダありCSVに変更する予定です。

`supplementary put` : `--csv`に渡すCSVファイルのフォーマットを「ヘッダなし」から「ヘッダあり」に変更しました。

---

annofabcli/annotation/remove_segmentation_overlap.py
annofabcli/annotation/subcommand_annotation.py
poetry.lock
tests/annotation/test_remove_segmentation_overlap.py

Annofabのインスタンスセグメンテーションは、別のインスタンスセグメンテーションと重ねることができます。
しかし、一般的なセグメンテーションでは「1ピクセルに対して1個のラベル（クラス）」が決まるので、塗りつぶしアノテーションを重ねる需要は少なそうです。
塗りつぶしアノテーションが重なっていても特に問題ありません。ただし、重なりを除去できれば、以下のメリットはあるかもしれません。
* Annofabで塗りつぶしアノテーションを確認しやすくなる。重なっていると見づらい
そこで、コマンドを作成することにしました。

`annotation remove_segmentation_overlap`コマンドを作成

---

annofabcli/statistics/list_annotation_count.py
annofabcli/statistics/list_annotation_duration.py
docs/command_reference/statistics/list_annotation_count.rst
docs/command_reference/statistics/list_annotation_count/out_by_input_data_attribute.csv
docs/command_reference/statistics/list_annotation_count/out_by_input_data_label.csv
docs/command_reference/statistics/list_annotation_count/out_by_task_attribute.csv
docs/command_reference/statistics/list_annotation_count/out_by_task_label.csv
docs/command_reference/statistics/list_annotation_duration.rst
tests/statistics/test_list_annotation_duration.py

以下のコマンドに対して、出力結果を次のように変更しました。
* `statistics list_annotation_count`
* `statistics list_annotation_duration`
アノテーションZIP内のJSONに従い、出力結果を修正しました。
* `phase` -> `task_phase`
* `phase_stage` -> `task_phase_stage`
* `status` -> `task_status`
タスク情報の出力がメインでないコマンドでは、「タスクの情報」であることを示すため、`task_`というプレフィックスを付けるようにしました。

`statistics list_annotation_count`,`statistics list_annotation_duration`コマンドの出力結果の一部の名前を変更しました。

---

annofabcli/statistics/visualization/dataframe/task.py

`タスクlist.csv`に以下の列が２列存在していたのを修正しました。
* inspection_is_skipped",
* acceptance_is_skipped",

`statistics visualize` : `タスクlist.csv`の列の重複を修正しました。

---

annofabcli/__init__.py
annofabcli/__version__.py
pyproject.toml

* `uv build`ではPythonバージョンに関するclassifierが出力されないので、自分自身で記載するようにしました。

`--version`を指定したときに正しくバージョン情報が出力されるようにしました。

---

annofabcli/statistics/visualize_statistics.py
docs/command_reference/statistics/visualize.rst

プロジェクト名をディレクトリ名にすると、エスケープ処理が必要になる。
またはプロジェクト名は変わる可能性がある。
プロジェクトIDで出力した方が、長期的に見ると扱いやすいため。

`statistics visualize` : `--project_id`に複数のIDを指定したときに、出力先のディレクトリ名がプロジェクト名だったのをプロジェクトIDに変更しました。

---

annofabcli/statistics/list_annotation_area.py
annofabcli/statistics/list_annotation_attribute.py
annofabcli/statistics/list_annotation_attribute_filled_count.py
annofabcli/statistics/list_annotation_count.py
annofabcli/statistics/list_annotation_duration.py
annofabcli/statistics/list_video_duration.py
docs/command_reference/statistics/list_annotation_attribute.rst
docs/command_reference/statistics/list_annotation_attribute/out.csv
docs/command_reference/statistics/list_annotation_attribute_filled_count.rst
docs/command_reference/statistics/list_annotation_attribute_filled_count/out_by_input_data.csv
docs/command_reference/statistics/list_annotation_attribute_filled_count/out_by_task.csv
docs/command_reference/statistics/list_annotation_count.rst
docs/command_reference/statistics/list_annotation_count/out_by_input_data_attribute.csv
docs/command_reference/statistics/list_annotation_count/out_by_input_data_label.csv
docs/command_reference/statistics/list_annotation_count/out_by_task_attribute.csv
docs/command_reference/statistics/list_annotation_count/out_by_task_label.csv
docs/command_reference/statistics/list_annotation_duration.rst
docs/command_reference/statistics/list_annotation_duration/out_by_attribute.csv
docs/command_reference/statistics/list_annotation_duration/out_by_label.csv
docs/command_reference/statistics/list_video_duration.rst
docs/command_reference/statistics/list_video_duration/out.csv
tests/statistics/test_list_annotation_attribute_filled_count.py
tests/statistics/test_list_annotation_count.py
tests/statistics/test_list_annotation_duration.py
tests/statistics/test_visualize_annotation_duration.py

`list_annotation_count`コマンドなどは、`--project_id`を指定しなくても実行できます。
出力結果をあとから見返した際、どのプロジェクトに関するものか知りたい場合があるので、`project_id`も出力するようにしました。

`statistics`系コマンドで、`project_id`も出力するようにしました。

---

annofabcli/task/list_tasks_added_task_history.py

関連issue #1220
タスクが0件のときも出力するようにしました。

`task list_added_task_history`の出力するCSVに、`project_id`を出力するようにしました。

---

annofabcli/annotation_specs/attribute_restriction.py
docs/command_reference/annotation_specs/list_attribute_restriction.rst
tests/annotation_specs/test_attribute_restriction.py

排他選択属性の場合は、`EQUALS '選択肢ID'`で出力していました。
知りたいのは選択肢IDではなく選択肢名なので、`EQUALS '選択肢名'`と出力するようにしました。
選択肢IDが空文字列でも警告なく出力するようにしました。

`annotation_specs list_attribute_restriction` : 選択肢IDが空文字でも警告メッセージなく出力するようにしました。

---

annofabcli/stat_visualization/write_performance_rating_csv.py
annofabcli/statistics/visualization/dataframe/project_performance.py
docs/command_reference/stat_visualization/write_performance_rating_csv.rst
docs/command_reference/stat_visualization/write_performance_rating_csv/out/annotation_productivity_deviation.csv
docs/command_reference/stat_visualization/write_performance_rating_csv/out/annotation_productivity_rank.csv
tests/statistics/visualization/test_write_performance_rating_csv.py

* 1行目：ディレクトリ名
* 2行目：評価指標
* 1行目：ディレクトリ名
* 2行目：プロジェクト名（`project_info.json`から読み込む）
* 3行目：評価指標

`stat_visualization write_performance_rating_csv`：出力結果のCSVのヘッダ行を2行から3行に変えました。

---

annofabcli/annotation/import_annotation.py

`--annotation`にZIPファイルを指定したときに、`--parallelism 2`を指定すると、以下のエラーが発生します。
```
TypeError: cannot pickle '_thread.RLock' object
```
事前にメモリに共有したり、ZIPファイルを展開すれば、multiprocessingで処理できますが、そこまでやる必要はなさそうなので、コマンドライン引数のバリデーションではじくようにしました。
また、This reverts commit 2167e183757b56fa2dee38674c5416de13068673. を実施しました。

`annotation import` : `--annotation`にZIPファイルを指定したときに並列度を指定できないようにする
