annofabcli/__main__.py, annofabcli/print_specs.py
新コマンド体系にはまだ合わせてないです。
調整お願いします。
=> アノテーション仕様出力サブコマンドを作った

README.md, annofabcli/project_member/copy_project_members.py, annofabcli/project_member/put_project_members.py, annofabcli/project_member/subcommand_project_member.py, tests/data/project_members.csv, tests/test_local_project_member.py, tests/test_main.py
=> CSVでプロジェクトメンバを一括に登録できるようにする

Makefile, Pipfile.lock, README.md, annofabcli/common/facade.py, annofabcli/project_member/list_users.py, tests/test_main.py
=> [project_member list] 脱退したメンバ、組織外のメンバを表示/非表示切り替えられるようにする

Pipfile.lock, README.md, annofabcli/common/utils.py, annofabcli/input_data/put_input_data.py, annofabcli/input_data/subcommand_input_data.py, annofabcli/project/copy_project.py, annofabcli/project_member/put_project_members.py, setup.py, tests/data/input_data.csv, tests/data/input_data2.csv, tests/test_local_input_data.py, tests/test_main.py
=> CSVから入力データを登録するコマンドの新規作成

annofabcli/task/delete_tasks.py, annofabcli/task/subcommand_task.py
=> [task delete] 新規追加

Pipfile.lock, annofabcli/common/dataclasses.py, annofabcli/input_data/put_input_data.py, annofabcli/project/copy_project.py, annofabcli/project/download.py, setup.py, tests/test_main.py
以下のコマンドに`--wait_options`を他のコマンドにも付ける。
* `input_data put`
* `project copy`
=> `--wait_options`を他のコマンドにも付ける

annofabcli/common/utils.py
=> windowsで開いても文字化けしないようにencode修正

annofabcli/common/utils.py
`to_csv_kwargs = None` の場合は展開しないようにしました
=> to_csv_kwargs = None の場合に**で展開出来ずに死ぬところを修正

annofabcli/project/list_project.py, tests/test_main.py
=> [project list] `--project_id`でプロジェクト情報を取得できるようにする

annofabcli/experimental/list_labor_worktime.py, annofabcli/experimental/utils.py
aftime・労務情報が無い場合の修正
出力形式を四捨五入させる修正
=> aftimeが無い場合にコケる等修正

annofabcli/experimental/list_labor_worktime.py, annofabcli/experimental/utils.py
=> BOM付きで出力するように修正

annofabcli/experimental/list_labor_worktime.py, annofabcli/experimental/utils.py
* タイポ修正
* column_listの場合にprojectごとに分けて出力できる機能追加
=> project毎の集計を追加、タイポなど

annofabcli/experimental/utils.py
=> project_title追加

annofabcli/experimental/list_labor_worktime.py, annofabcli/experimental/utils.py, annofabcli/labor/list_worktime_by_user.py, tests/data/experimental/worktime-per-project-date.csv, tests/test_experimental.py
* `explerimental list_labor_worktime`：biographyが空の場合出力されない
* `labro list_worktime_by_user`：biographyが空の場合、0が出力される
=> [explerimental list_labor_worktime] biographyが空の場合出力されない問題を解決

README.md, annofabcli/supplementary/put_supplementary_data.py, annofabcli/supplementary/subcommand_supplementary.py
fixes #123 
input_data put を参考に実装してみました。
=> 補助情報を登録するコマンドの追加

README.md, docker/Dockerfile
=> #353 dockerのENTRYPOINTにannofabcliを追加

annofabcli/annotation/import_annotation.py, annofabcli/annotation/restore_anotation.py, annofabcli/common/facade.py, annofabcli/project_member/delete_users.py, annofabcli/project_member/invite_users.py, poetry.lock, pyproject.toml, tests/test_main.py
進行中のプロジェクトのみ、対象にしていた
進行中のプロジェクトだけでなく、停止中のプロジェクトも対象にした。
進行中のプロジェクトだけを対象にしたいケースが少ないため。
=> `project_member invite`, `project_member delete`の`--organization`を指定したときに、進行中のプロジェクトだけでなく停止中のプロジェクトも対象にする。 

.devcontainer/devcontainer.json, annofabcli/common/download.py, annofabcli/input_data/put_input_data.py, annofabcli/job/delete_job.py, annofabcli/job/list_job.py, annofabcli/job/list_last_job.py, annofabcli/job/wait_job.py, annofabcli/project/copy_project.py, annofabcli/project/download.py, annofabcli/project/update_annotation_zip.py, annofabcli/statistics/database.py, annofabcli/statistics/table.py, annofabcli/task/put_tasks.py, docs/requirements.txt, poetry.lock, pyproject.toml, tests/test_common_download.py, tests/test_common_facade.py, tests/test_experimental.py, tests/test_instruction.py, tests/test_job.py, tests/test_labor.py, tests/test_project.py, tests/test_project_member.py, tests/test_statistics.py, tests/test_task_history.py
* annofabapiのバージョンアップにより、annofabapi.models.JobType -> annofabapi.models.ProjectJobType に変更した
=> annofabapi.models.JobType -> annofabapi.models.ProjectJobTypeに変更

.devcontainer/Dockerfile, .travis.yml, .vscode/cspell.json, annofabcli/annotation/list_annotation.py, annofabcli/annotation_specs/list_annotation_specs_label.py, annofabcli/annotation_specs/print_label_color.py, annofabcli/common/facade.py, annofabcli/common/visualize.py, annofabcli/project/diff_projects.py, annofabcli/statistics/list_annotation_count.py, annofabcli/statistics/table.py, docs/requirements.txt
```
annofabcli annotation list
annofabcli annotation_specs list_label
annofabcli annotation_specs list_label_color
annofabcli project diff
annofabcli statistics list_annotation_count
```
=> AnnotationSpecsV1からAnnotationSpecsV2に移行

docs/requirements.txt
=> readthedocs version

docs/requirements.txt, poetry.lock, pyproject.toml
=> `docs/requirements.txt`に`sphinx-argparse`を追加

annofabcli/labor/list_worktime.py
* 出力対象でないプロジェクトは、アクセスできるか確認しないようにする
=> `labor list_worktime`：改善

README.md
=> travisci のbadgeを修正

annofabcli/statistics/visualization/dataframe/user_performance.py, annofabcli/statistics/visualization/dataframe/whole_productivity_per_date.py
* `line-graph/折れ線-横軸_教師付開始日-全体.html`：アノテーションあたり作業時間の凡例の文言の間違いを修正
=> statistics visualize：折れ線グラフの微修正

.travis.yml, annofabcli/common/cli.py, annofabcli/common/utils.py, annofabcli/data/logging.yaml, annofabcli/experimental/subcommand_experimental.py, annofabcli/statistics/visualization/dataframe/worktime_per_date.py, annofabcli/supplementary/list_supplementary_data.py, poetry.lock, pyproject.toml, tests/test_experimental.py, tests/test_labor.py, tests/test_local_experimental.py, tests/test_local_labor.py
"--debug"を付けたときに、HTTPリクエストの中身とレスポンスのステータスコードを出力するようにした。
=> "--debug"を付けたときに、HTTPリクエストの中身とレスポンスのステータスコードを出力する

docs/command_reference/annotation/list_count.rst
=> annotation list_count.rst のtypoを修正

README.md, annofabcli/comment/list_comment.py, annofabcli/common/visualize.py, annofabcli/input_data/list_input_data.py, annofabcli/inspection_comment/list_inspections.py, annofabcli/project/copy_project.py, annofabcli/statistics/database.py, annofabcli/statistics/linegraph.py, docs/command_reference/comment/download.rst, docs/command_reference/comment/list.rst, docs/command_reference/input_data/download.rst, docs/command_reference/input_data/list.rst, docs/command_reference/project/copy.rst, docs/command_reference/task/download.rst, docs/command_reference/task_history/download.rst, docs/command_reference/task_history_event/download.rst, poetry.lock, pyproject.toml
close #775 
close #689 
* `download`コマンドのドキュメントに出力結果を記載する
* 型ヒントやtypoの修正
* `comment list`コマンドの出力結果に、以下の列を追加しました。
* user_id
* username
* label_name_en
* label_name_ja
* phase_name_en
* phrase_name_ja
* `project copy`コマンドのオプションを修正しました。
=> `project copy`, `comment list`コマンドの結果

annofabcli/stat_visualization/mask_visualization_dir.py, annofabcli/statistics/linegraph.py, annofabcli/statistics/visualization/dataframe/cumulative_productivity.py, annofabcli/statistics/visualization/dataframe/productivity_per_date.py, annofabcli/statistics/visualization/dataframe/whole_productivity_per_date.py, annofabcli/statistics/visualization/dataframe/worktime_per_date.py, annofabcli/statistics/visualization/project_dir.py, poetry.lock
* ファイルが存在しなかったときの挙動を変更
* 縦軸が2つある折れ線グラフの縦軸範囲を適切にした。
* ユーザーごとにプロットする折れ線グラフで、「すべての折れ線を表示する」ボタンを追加した。
=> [stat_visualization mask_user_info] ファイルが存在しなかったときの挙動を変更

README.md, annofabcli/comment/list_all_comment.py, annofabcli/comment/subcommand_comment.py, docs/command_reference/comment/index.rst, docs/command_reference/comment/list_all.rst, tests/test_comment.py
=> `comment list_all`コマンドの作成

annofabcli/__main__.py, annofabcli/common/cli.py, annofabcli/my_account/get_my_account.py, annofabcli/my_account/subcommand_my_account.py, annofabcli/organization/list_organization.py, annofabcli/organization/subcommand_organization.py, annofabcli/project/put_project.py, annofabcli/project/subcommand_project.py, annofabcli/project/update_annotation_zip.py, annofabcli/statistics/table.py, annofabcli/statistics/visualization/dataframe/project_performance.py, annofabcli/statistics/visualize_statistics.py, docs/command_reference/index.rst, docs/command_reference/my_account/get.rst, docs/command_reference/my_account/index.rst, docs/command_reference/organization/index.rst, docs/command_reference/organization/list.rst, docs/command_reference/project/index.rst, docs/command_reference/project/put.rst, poetry.lock, tests/test_my_account.py, tests/test_organization.py, tests/test_project.py, tests/test_task.py
close #862 
close #861
以下のコマンドを作成しました。
* project put
* my_account get
* organization list
=> `my_account get`, `organization list`, `project put` コマンドの作成

annofabcli/statistics/histogram.py, annofabcli/statistics/linegraph.py, annofabcli/statistics/scatter.py, annofabcli/statistics/visualization/dataframe/cumulative_productivity.py, annofabcli/statistics/visualization/dataframe/productivity_per_date.py, annofabcli/statistics/visualization/dataframe/task.py, annofabcli/statistics/visualization/dataframe/user_performance.py, annofabcli/statistics/visualization/dataframe/whole_productivity_per_date.py, annofabcli/statistics/visualization/dataframe/worktime_per_date.py, annofabcli/statistics/visualize_annotation_count.py, poetry.lock, pyproject.toml, tests/statistics/visualization/dataframe/test_cumulative_productivity.py, tests/statistics/visualization/dataframe/test_user_performance.py
bokeh2.4から3.0にバージョンアップして、それに伴いコードを修正しました。
=> bokeh2.4から3.0にバージョンアップ

Makefile, annofabcli/filesystem/mask_user_info.py, pyproject.toml, tests/annotation_specs/get_annotation_specs_with_choice_id_replaced.py, tests/annotation_specs/test_get_annotation_specs_with_attribute_id_replaced.py, tests/annotation_specs/test_get_annotation_specs_with_label_id_replaced.py, tests/annotation_specs/test_list_attribute_restriction.py, tests/common/test_cli.py, tests/common/test_download.py, tests/common/test_utils.py, tests/filesystem/test_mask_user_info.py, tests/project_member/test_change_project_members.py, tests/statistics/test_list_worktime.py, tests/statistics/visualization/dataframe/test_whole_productivity_per_date.py, tests/test_annotation.py, tests/test_supplementary.py
* 既存のテストコードで、assertしていない箇所をassertするようにした
* Makefileでfomat, lintタスクの内容を変更した
* flake8-pytest-styleも除外した
=> Ruffをフォーマッターとして利用する

.devcontainer/devcontainer.json, .vscode/settings.json, Makefile, pylintrc
https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff
`--config`で設定ファイルを指定したけど反映されていないような気がする。。。
=> vscodeのRuffプラグインを導入

.readthedocs.yaml
https://github.com/readthedocs/readthedocs.org/issues/10290
=> ReadTheDocsのsphinx buildで失敗したので、設定ファイルを更新する

.readthedocs.yaml, docs/command_reference/input_data/change_name.rst
以下のsphinx buildエラーを修正しました。
https://readthedocs.org/projects/annofab-cli/builds/20580440/
```
/home/docs/checkouts/readthedocs.org/user_builds/annofab-cli/checkouts/latest/docs/command_reference/filesystem/merge_annotation.rst:115: ERROR: Failed to import "add_parser" from "annofabcli.filesystem.merge_annotation".
No module named 'annofabcli'
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/annofab-cli/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 285, in build_main
app.build(args.force_all, args.filenames)
File "/home/docs/checkouts/readthedocs.org/user_builds/annofab-cli/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 353, in build
self.builder.build_update()
File …
```
=> `readthedocs.yaml`の設定漏れを修正

.devcontainer/Dockerfile, annofabcli/common/cli.py, annofabcli/common/exceptions.py, poetry.lock, pyproject.toml
現状、MFAが有効化されたユーザーはannofabcliを実行できません。
このPRでは、annofabcliの実行時にそれが分かるメッセージを追加しています。 https://github.com/kurusugawa-computer/annofab-cli/pull/1099/commits/35cd303cf47a9626c049227273f081606791c89a
=> Annofabリリースに伴う更新

annofabcli/annotation_specs/export_annotation_specs.py, annofabcli/annotation_specs/list_annotation_specs_label.py, annofabcli/annotation_specs/subcommand_annotation_specs.py, annofabcli/common/cli.py, annofabcli/common/utils.py, annofabcli/statistics/summarize_task_count_by_task_id_group.py, annofabcli/statistics/summarize_task_count_by_user.py, docs/command_reference/annotation_specs/export.rst, docs/command_reference/annotation_specs/index.rst, pylintrc, tests/test_annotation_specs.py
いずれ`annotation_specs import`コマンドも作成する。
=> `annotation_specs export`コマンドの作成

Makefile, annofabcli/statistics/histogram.py, annofabcli/statistics/visualize_annotation_count.py, annofabcli/statistics/visualize_annotation_duration.py, pyproject.toml
=> `statistics visualize_video_duration` : グラフに表示している標準偏差を標本標準偏差から母標準偏差に変更する

annofabcli/annotation/list_annotation_count.py, annofabcli/annotation_specs/list_attribute_restriction.py, annofabcli/input_data/change_input_data_name.py, annofabcli/input_data/update_metadata_of_input_data.py, annofabcli/instruction/upload_instruction.py, annofabcli/job/wait_job.py, annofabcli/statistics/list_annotation_duration.py, annofabcli/statistics/list_worktime.py, annofabcli/task/update_metadata_of_task.py, annofabcli/task_history_event/list_all_task_history_event.py, annofabcli/task_history_event/list_worktime.py, poetry.lock, pylintrc
* ログメッセージの修正
* pylint,mypyのアップデートによる修正
=> ログメッセージの修正

annofabcli/annotation_specs/list_annotation_specs_attribute.py, annofabcli/annotation_specs/list_annotation_specs_choice.py, annofabcli/annotation_specs/list_annotation_specs_label.py, annofabcli/annotation_specs/list_attribute_restriction.py, annofabcli/common/annofab/project.py
以下のコマンドに`--annotation_specs_json`引数を追加しました。アノテーション仕様のJSONから出力したいときがあったので、追加しました。
* `annotation_specs list_label`
* `annotation_specs list_attribute`
* `annotation_specs list_choice`
* `annotation_specs list_restriction`
=> `annotation_specs` : `list_label`コマンドなどに`--annotation_specs_json`引数を指定しました。

annofabcli/input_data/list_input_data.py
`--output`を指定しないと、`TypeError`が発生しました。
```
$ annofabcli input_data list  --project_id prj1
...
File "/home/yuji/.pyenv/versions/3.12.4/lib/python3.12/site-packages/annofabcli/input_data/list_input_data.py", line 186, in main
output_file=Path(args.output),
^^^^^^^^^^^^^^^^^
File "/home/yuji/.pyenv/versions/3.12.4/lib/python3.12/pathlib.py", line 1162, in __init__
super().__init__(*args)
File "/home/yuji/.pyenv/versions/3.12.4/lib/python3.12/pathlib.py", line 373, in __init__
raise TypeError(
TypeError: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'NoneType'
```
* コマンドライン引数 `--average_input_data_id_length` を削除しました。理由は以下の通りです。
* 説明を見ただけでは使うのが難しい
* この引数は`getTasks` APIの実行回数（コマンドの実行時間）に影響するだけで、出力結果には影響しない
=> `input_data list` : `--output`を指定しないときに`TypeError`が発生する不具合を修正しました。

.github/workflows/release.yml, pyproject.toml
=> pyinstallerによるwindows用のexeファイルの生成処理を変更しました

annofabcli/statistics/visualization/dataframe/whole_productivity_per_date.py, tests/statistics/visualization/dataframe/test_whole_productivity_per_date.py
=> `statistics visualize`: `折れ線-横軸_教師付開始日-全体.html`にユーザー独自の生産量を追加する

annofabcli/statistics/visualization/dataframe/cumulative_productivity.py, annofabcli/statistics/visualization/project_dir.py, annofabcli/statistics/visualize_statistics.py, tests/statistics/visualization/dataframe/test_cumulative_productivity.py
=> `statistics visualize` : `累積折れ線-横軸_xxx-教師付者用.html`グラフに独自の生産量をプロットする

annofabcli/stat_visualization/mask_visualization_dir.py, annofabcli/stat_visualization/merge_visualization_dir.py, annofabcli/stat_visualization/write_graph.py, annofabcli/statistics/visualization/dataframe/productivity_per_date.py, annofabcli/statistics/visualization/project_dir.py, annofabcli/statistics/visualize_statistics.py, tests/statistics/visualization/dataframe/test_productivity_per_date.py
=> `statistics visualize` : `折れ線-横軸_教師付開始日-縦軸_XXXあたりの指標-教師付者用.html`を独自生産量でプロットできるようにする

annofabcli/stat_visualization/mask_visualization_dir.py, annofabcli/stat_visualization/merge_visualization_dir.py, annofabcli/stat_visualization/write_graph.py, annofabcli/statistics/visualization/dataframe/cumulative_productivity.py, annofabcli/statistics/visualization/dataframe/productivity_per_date.py, annofabcli/statistics/visualization/project_dir.py, annofabcli/statistics/visualize_statistics.py
* `ProjectDir`のインスタンスに`custom_production_volume_list`を持たせるようにしました。
* いくつかの不具合を修正しました。
=> `stat_visualization` : リファクタリング

annofabcli/stat_visualization/mask_visualization_dir.py, annofabcli/stat_visualization/merge_visualization_dir.py, annofabcli/stat_visualization/summarize_whole_performance_csv.py, annofabcli/stat_visualization/write_graph.py, annofabcli/stat_visualization/write_performance_rating_csv.py, annofabcli/statistics/visualization/dataframe/project_performance.py, annofabcli/statistics/visualize_statistics.py, docs/command_reference/statistics/visualize.rst, tests/statistics/visualization/test_write_performance_rating_csv.py
* `write_performance_rating_csv`コマンドの修正
=> `statistics visualize` : `--custom_production_volume`に関する説明を追加

annofabcli/statistics/list_video_duration.py, annofabcli/statistics/visualization/dataframe/productivity_per_date.py, docs/command_reference/statistics/list_video_duration.rst, docs/command_reference/statistics/list_video_duration/out.csv
入力データがいつ登録されたものかを確認したいケースがあったので、`input_data_updated_datetime`を出力するようにしました。
=> `statistics list_video_duration` : 入力データの更新日時 `input_data_updated_datetime`を出力するようにしました。

annofabcli/annotation/list_annotation_count.py, docs/command_reference/annotation/list_count.rst, poetry.lock
* `--format`引数を追加しいてJSONで出力できるようにしました。
* 取得したアノテーションの件数が0件のときでも、出力するようにしました。 #1220
=> `annotation list_count` : `--format`引数を追加しいてJSONで出力できるようにしました。

docs/command_reference/task/copy.rst, docs/examples/http_private_storage.rst
以下のドキュメントを更新しました。
* `task copy` コマンド
* HTTPプライベートストレージの運用例 https://annofab-cli.readthedocs.io/ja/latest/examples/http_private_storage.html
=> ドキュメントを更新しました。

annofabcli/annotation/change_annotation_attributes.py, annofabcli/annotation/change_annotation_properties.py, annofabcli/annotation/copy_annotation.py, annofabcli/annotation/dump_annotation.py, annofabcli/annotation/import_annotation.py, annofabcli/annotation/restore_annotation.py, annofabcli/comment/delete_comment.py, annofabcli/comment/put_inspection_comment.py, annofabcli/comment/put_inspection_comment_simply.py, annofabcli/comment/put_onhold_comment.py, annofabcli/comment/put_onhold_comment_simply.py, annofabcli/common/cli.py, annofabcli/input_data/change_input_data_name.py, annofabcli/input_data/delete_metadata_key_of_input_data.py, annofabcli/input_data/put_input_data.py, annofabcli/input_data/update_metadata_of_input_data.py, annofabcli/project/update_annotation_zip.py, annofabcli/statistics/visualize_statistics.py, annofabcli/supplementary/list_supplementary_data.py, annofabcli/supplementary/put_supplementary_data.py, annofabcli/task/cancel_acceptance.py, annofabcli/task/change_operator.py, annofabcli/task/change_status_to_break.py, annofabcli/task/change_status_to_on_hold.py, annofabcli/task/complete_tasks.py, annofabcli/task/copy_tasks.py, annofabcli/task/delete_metadata_key_of_task.py, annofabcli/task/put_tasks.py, annofabcli/task/reject_tasks.py, annofabcli/task/update_metadata_of_task.py
=> "--parallelism"に指定できる値を最大4にしました。

annofabcli/annotation_specs/export_annotation_specs.py, annofabcli/statistics/list_annotation_attribute.py, annofabcli/statistics/subcommand_statistics.py, docs/command_reference/statistics/index.rst, docs/command_reference/statistics/list_annotation_attribute.rst, docs/command_reference/statistics/list_annotation_attribute/out.csv, pyproject.toml, tests/test_statistics.py
=> `statisitcs list_annotation_attribute`コマンドの作成

annofabcli/input_data/put_input_data.py, annofabcli/supplementary/delete_supplementary_data.py, annofabcli/supplementary/put_supplementary_data.py, docs/command_reference/supplementary/put.rst, tests/input_data/test_put_input_data.py, tests/supplementary/test_put_supplementary_data.py
#1347 に関連した内容です。変更内容は #1347 を参照してください。
* 補助
=> `supplementary put` : `supplementary_data_id`が指定されないときに、UUIDでなく`supplementary_data_name`に近い値を設定するようにしました。

annofabcli/input_data/update_metadata_of_input_data.py, annofabcli/statistics/list_annotation_count.py, annofabcli/statistics/list_annotation_duration.py, annofabcli/statistics/visualization/dataframe/productivity_per_date.py, annofabcli/statistics/visualization/dataframe/user_performance.py, annofabcli/statistics/visualization/dataframe/whole_performance.py, annofabcli/statistics/visualization/dataframe/whole_productivity_per_date.py, annofabcli/statistics/visualization/dataframe/worktime_per_date.py, annofabcli/task/update_metadata_of_task.py, poetry.lock, pyproject.toml
=> poetry update: Ruffをv0.11にする

annofabcli/annotation/merge_segmentation.py, annofabcli/annotation/remove_segmentation_overlap.py, annofabcli/annotation/subcommand_annotation.py, docs/command_reference/annotation/index.rst, docs/command_reference/annotation/merge_segmentation.rst, docs/command_reference/annotation/remove_segmentation_overlap.rst, tests/annotation/test_merge_segmentation.py
=> `annotation merge_segmentation`コマンドを作成

annofabcli/task/list_tasks_added_task_history.py, poetry.lock, tests/task/test_list_tasks_added_task_history.py
* account_idからuser_id,user_nameに移動する関数は工夫する
=> `task list_added_task_history` : リファクタリング。staticmethodから関数に移動

annofabcli/annotation_specs/put_label_color.py, annofabcli/comment/delete_comment.py, annofabcli/comment/put_inspection_comment.py, annofabcli/comment/put_onhold_comment.py, annofabcli/input_data/change_input_data_name.py, annofabcli/input_data/put_input_data.py, annofabcli/task/put_tasks.py
=> `--json`引数の型をバリデーションする

annofabcli/__version__.py, pyproject.toml
`__version__`は`__init__.py`で設定するようにしたので削除しました。
=> remove "__version__.py"

annofabcli/annotation/import_annotation.py
並列実行すると以下のエラーが発生した。
```
TypeError: cannot pickle '_thread.RLock' object
```
=> `annotation import` : 並列実行でエラーが発生しないようにする

annofabcli/project/subcommand_project.py, annofabcli/project/update_project.py, docs/command_reference/project/index.rst, docs/command_reference/project/update.rst, tests/data/project/update/test_projects.csv, tests/test_project_update.py
=> `project update`コマンドの作成

annofabcli/statistics/visualization/dataframe/annotation_count.py, annofabcli/statistics/visualize_statistics.py
=> `statistics visualize` : `annotation_count`に含める/除外するラベルを指定できるようにしました。
